/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSalesRevenue200Item = {
  date: string;
  id: number;
  newCustomers: number;
  upCrossSelling: number;
};
