/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */

export type TodaysStatsResponseSales = {
  /** Label for sales */
  label: string;
  /** Sales value */
  value: number;
};
