/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface UserDto {
  id: number;
  name: string;
  email: string;
  avatar: string;
}
