/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { TodaysStatsResponseCost } from './todaysStatsResponseCost';
import type { TodaysStatsResponseProfit } from './todaysStatsResponseProfit';
import type { TodaysStatsResponseSales } from './todaysStatsResponseSales';

export interface TodaysStatsResponse {
  cost: TodaysStatsResponseCost;
  profit: TodaysStatsResponseProfit;
  sales: TodaysStatsResponseSales;
}
