/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface UserDto {
  _id: string;
  companyBalance: number;
  creationTime: string;
  email: string;
  password: string;
  userBalance: number;
}
